name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight
  workflow_dispatch: # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: rishabh-108272
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated snake contribution grid"
          default_author: github_actions
          push: true
